Add Docker containers
codex-team/uptime-monitor.server pull request #1
Opened 2018-11-06 17:27 UTC by ilyatos

2018-11-06 17:28 UTC, talyguryn approved these changes

2018-11-06 17:32 UTC, khaydarov requested changes

2018-11-06 17:32 UTC, khaydarov commented on docker-compose.yml
> +      - '27017:27017'
Вот это необязательно, только если тебе не нужно из своей машины обращаться к докер-контейнеру. Достаточно указать в links, а докер сам сможет прокинуть нужный порт

2018-11-06 17:39 UTC, khaydarov approved these changes

2018-11-06 18:30 UTC, n0str requested changes

2018-11-06 18:30 UTC, n0str commented on docker-compose.yml
> +      - '8118:8080'
Это очень рандомный порт. Предлагаю позволить каждому собирать свою сборку и устанавливать те порты на локальной машине, которые им нужны.
Есть куча способов это сделать, например: https://docs.docker.com/compose/environment-variables/#the-env-file

2018-11-06 18:30 UTC, n0str commented on docker-compose.yml
> +      - '8118:8080'
И почему порт внутри машины 8080? Это задумано? Чем там занят 80?

2018-11-07 07:57 UTC, talyguryn commented on docker-compose.yml
> +      - '8118:8080'
> Чем там занят 80?

стандартной заглушкой nginx. проще добавить конфиг сайта и сказать ему слушать порт 8080, чем ещё и удалять дефолтный конфиг.
по факту можно и на 80 бросить, но от этого вообще ничего не поменяется

2018-11-07 15:14 UTC, ilyatos commented on docker-compose.yml
> +      - '27017:27017'
@khaydarov Я ведь хочу получать доступ к контейнеру через приложения для просмотра бд. И как раз получается, мне нужно обращаться со своей машины. Или нет?

2018-11-07 17:51 UTC, ilyatos commented on docker-compose.yml
> +      - '8118:8080'
Добавил поддержку .env. Необходимо переименовать .env.example -> .env и прописать, какие порты будут использованы на своей машине.

2018-11-08 05:21 UTC, n0str approved these changes

2018-11-08 05:21 UTC, neSpecc approved these changes

2018-11-08 09:10 UTC, merged