Improve project layout
codex-team/uptime-monitor.server pull request #14
Opened 2019-04-04 18:05 UTC by khaydarov

2019-04-09 16:27 UTC, ilyatos requested changes

2019-04-09 16:27 UTC, ilyatos commented on src/Components/Base/Mongo.php
> +                sprintf('mongodb://%s:%s', Configs::get('mongo')['host'], Configs::get('mongo')['port']), [],
Зачем такие сложности? можно же задействовать .env

2019-04-09 16:27 UTC, ilyatos commented on src/Schema/TypeRegistry.php
Почему так, а не как было раньше?

2019-04-09 16:27 UTC, ilyatos commented on app/init.php
> +<?php
Обычно файл называют bootstrap.php, или нет?

2019-04-09 16:28 UTC, khaydarov commented on app/init.php
> +<?php
ага, давай назовем boostrap

2019-04-09 16:28 UTC, khaydarov commented on src/Components/Base/Mongo.php
> +                sprintf('mongodb://%s:%s', Configs::get('mongo')['host'], Configs::get('mongo')['port']), [],
в env нельзя структурировать конфиги, там обычный key=value

2019-04-09 16:29 UTC, ilyatos commented on src/Components/Base/Mongo.php
> +                sprintf('mongodb://%s:%s', Configs::get('mongo')['host'], Configs::get('mongo')['port']), [],
понял-принял

2019-04-09 16:29 UTC, khaydarov commented on src/Components/Base/Mongo.php
> +                sprintf('mongodb://%s:%s', Configs::get('mongo')['host'], Configs::get('mongo')['port']), [],
в yaml можно хранить более сложную структуру, удобна еще в использовании.

2019-04-09 16:29 UTC, khaydarov commented on src/Schema/TypeRegistry.php
вот это хз, я fix-ером прошелся, он сам так сделал

2019-04-10 11:14 UTC, neSpecc approved these changes

2019-04-10 11:15 UTC, ilyatos approved these changes

2019-04-10 19:50 UTC, n0str approved these changes

2019-04-10 19:52 UTC, merged