Registration
codex-team/uptime-monitor.server pull request #16
Opened 2019-04-13 17:50 UTC by ilyatos

2019-04-17 05:32 UTC, neSpecc requested changes

2019-04-17 05:32 UTC, neSpecc commented on app/config/development.yml
> +mailgun:
сразу нужно написать док, откуда эти данные брать для разворачивания. Где-нибудь в docs/devrlopers.md

2019-04-17 05:32 UTC, neSpecc commented on src/Components/Base/Mail.php
> +            $mailer->Port = 587;
это надо хардкодить? откуда цифра?

2019-04-17 05:32 UTC, neSpecc commented on src/Components/Base/Twig.php
> +    private const TEMPLATES_PATH = ROOT . '/src/views/templates';
уверен что нужно и /views и /templates? мне кажется лишняя вложенность, надо что-то одно оставить

2019-04-17 05:32 UTC, neSpecc commented on src/Components/Base/Mail.php
> + * Class Mail
давай во всех классах, где используется синглтон, напишем сверху об этом, чтобы сразу понятно было

2019-04-17 05:32 UTC, neSpecc commented on src/Components/Base/Twig.php
> +    private const TEMPLATES_PATH = ROOT . '/src/views/templates';
константы тоже надо документировать

2019-04-17 05:32 UTC, neSpecc commented on src/Components/Models/BaseModel.php
> +        if (array_key_exists('_id', $args) && $args['_id'] !== null) {
можно просто `!empty($args['_id'])`

2019-04-17 05:32 UTC, neSpecc commented on src/Components/Models/Membership.php
> +        return Project::findById($this->projectId);
а теперь главный вопрос, почему все на статик функциях, а не `new Project($this->projectId)`

2019-04-17 10:18 UTC, ilyatos commented on src/Components/Models/Membership.php
> +        return Project::findById($this->projectId);
Статик функции только для поиска, они возвращают инстанс модели + достаточно просто оперировать такими вызовами +  краткость в коде. А через конструктор идёт заполнение модели.

2019-04-17 14:34 UTC, ilyatos commented on src/Components/Base/Mail.php
> + * Class Mail
Там не совсем синглтон. Возвращается не объект класса, а внутренняя переменная, которая определяется один раз. По сути синглтон выполняется только для этой переменной

2019-04-22 08:01 UTC, neSpecc requested changes

2019-04-22 08:01 UTC, neSpecc commented on src/Components/Models/User.php
> +        return substr(str_shuffle($chars), 0, $length);
плохой способ

2019-04-22 08:01 UTC, neSpecc commented on src/Components/Models/User.php
> +        return substr(str_shuffle($chars), 0, $length);
лучше использовать `openssl_random_pseudo_bytes`

2019-04-22 08:01 UTC, neSpecc commented on src/Components/Base/Twig.php
> +         * TODO: реализовать
сразу можем сделать это?

2019-04-22 08:01 UTC, neSpecc commented on src/Schema/Types/Requests/Mutation.php
> +                                //TODO: как вернуть ошибку??
сразу надо допилить

2019-04-23 10:17 UTC, ilyatos commented on src/Schema/Types/Requests/Mutation.php
> +                                //TODO: как вернуть ошибку??
согласен

2019-04-23 10:17 UTC, ilyatos commented on src/Components/Base/Twig.php
> +         * TODO: реализовать
много работы тут, лучше закрыть сейчас то, что есть

2019-04-23 19:46 UTC, khaydarov requested changes

2019-04-23 19:46 UTC, khaydarov commented on public/index.php
> +    $debug = getenv('DEBUG') ? Debug::INCLUDE_DEBUG_MESSAGE | Debug::INCLUDE_TRACE: false;
https://github.com/codex-team/hawk.api/blob/master/src/Components/Base/Config.php#L78

можешь сюда добавить `self::$_isDebug === "true"` плиз?

2019-04-23 19:46 UTC, khaydarov commented on public/index.php
> +    $debug = getenv('DEBUG') ? Debug::INCLUDE_DEBUG_MESSAGE | Debug::INCLUDE_TRACE: false;
```suggestion
    $debug = Config::isDebug() ? Debug::INCLUDE_DEBUG_MESSAGE | Debug::INCLUDE_TRACE: false;
```

2019-04-23 19:46 UTC, khaydarov commented on src/Components/Base/Mail.php
> +    /** @var Mailgun */
```suggestion
    /** 
     * @var Mailgun 
     */
```

2019-04-23 19:46 UTC, khaydarov commented on src/Components/Base/Mail.php
> +    /** @var PHPMailer */
```suggestion
    /** 
     * @var PHPMailer 
     */
```

2019-04-23 19:46 UTC, khaydarov commented on src/Components/Base/Mail.php
> +     * @throws Exception
этот exception нигде не обрабатывается, давай его в этой же функции и отлавливать.

заверни в try ... catch и верни false

2019-04-23 19:46 UTC, khaydarov commented on src/Components/Base/Twig.php
> +
```suggestion
declare(strict_types=1);
```

2019-04-23 19:46 UTC, khaydarov commented on src/Components/Base/Twig.php
> +         * TODO: реализовать
Да, давайте отдельным реквестом это сделаем. Я добавлю gettext

2019-04-23 20:38 UTC, ilyatos commented on public/index.php
> +    $debug = getenv('DEBUG') ? Debug::INCLUDE_DEBUG_MESSAGE | Debug::INCLUDE_TRACE: false;
Окей, а почему переменные начинаются с _?

2019-04-25 07:35 UTC, khaydarov approved these changes

2019-04-26 08:16 UTC, neSpecc requested changes
Не актуальные доки.

- убрать лишнее из readme
- создать нормальную инструкцию по запуску на локали со всеми пунктами (сейчас там только `docker-compose up`)
- вынести Гайд по ручной установке окружения в отдельный док

2019-04-29 18:01 UTC, neSpecc approved these changes

2019-05-06 19:14 UTC, merged