GraphQl Schema
codex-team/uptime-monitor.server pull request #2
Opened 2018-11-14 20:55 UTC by ilyatos

2018-11-14 21:01 UTC, neSpecc requested changes

2018-11-14 21:01 UTC, neSpecc commented on monitor-api/schema/Types/User.php
> +                        'type' => Type::string(),
тут будет массив Project

2018-11-14 21:01 UTC, neSpecc commented on monitor-api/schema/Types/Query.php
> +                        'description' => 'Return all responses',
опиши, что имеется ввиду под response

2018-11-14 21:02 UTC, ilyatos commented on monitor-api/schema/Types/User.php
> +                        'type' => Type::string(),
Тестировал, забыл убрать)

2018-11-14 21:44 UTC, neSpecc approved these changes

2018-11-15 15:34 UTC, talyguryn approved these changes

2018-11-15 15:35 UTC, merged