Mutation+Database+Models
codex-team/uptime-monitor.server pull request #3
Opened 2018-11-18 19:05 UTC by ilyatos

2018-11-18 20:18 UTC, khaydarov requested changes

2018-11-18 20:18 UTC, khaydarov commented on monitor-api/.env.example
> +
лишняя строчка

2018-11-18 20:18 UTC, khaydarov commented on monitor-api/.env.example
> +#MONGO
пробел после #

2018-11-18 20:18 UTC, khaydarov commented on monitor-api/components/base/Error.php
> +
declare(strict_types=1);

2018-11-18 20:18 UTC, khaydarov commented on monitor-api/components/base/Mongo.php
> +
declare(strict_types=1);

2018-11-18 20:18 UTC, khaydarov commented on monitor-api/components/base/Mongo.php
> +            $domain = getenv('MONGO_HOST') ?? 'localhost';
этот кусок лучше вынести в конструктор, а то чет кривой синглтон получился.

2018-11-18 20:18 UTC, khaydarov commented on monitor-api/components/models/BaseModel.php
> +
declare(strict_types=1);

2018-11-18 20:18 UTC, khaydarov commented on monitor-api/components/models/BaseModel.php
> +    abstract public function sync(): void;
давай пустые функции поднимем выше

2018-11-18 20:18 UTC, khaydarov commented on monitor-api/components/models/BaseModel.php
> +     * @throws \Exception
Можно создать(на самом деле лучше) ModelException (название можешь придумать сам) и вызывать exception через его конструктор. Это делается для того, чтобы различать ошибки. Например, не всегда нужно отлавливать Exception, нужно падать так как дальше интерпретировать нет смысла. А если ты создашь свой класс ModelException, то ты точно (не всегда) знаешь ошибка была в момент обработки модели и что с ним делать

2018-11-18 20:18 UTC, khaydarov commented on monitor-api/components/models/BaseModel.php
> +                throw new \Exception("Record with _id = $id not found");
заменить на кастомный exception

2018-11-18 20:18 UTC, khaydarov commented on monitor-api/components/models/BaseModel.php
> +            $object = new static();
меня это немного смущает. Почему статик?

2018-11-18 20:18 UTC, khaydarov commented on monitor-api/components/models/BaseModel.php
> +    abstract public function collectionName(): string;
подними в начало

2018-11-18 20:18 UTC, khaydarov commented on monitor-api/components/models/User.php
> +        return 'users';
это в константу

2018-11-18 20:18 UTC, khaydarov commented on monitor-api/schema/Types/Mutation.php
> +
declare(strict_types=1);

2018-11-18 20:20 UTC, ilyatos commented on monitor-api/components/models/BaseModel.php
> +            $object = new static();
Позднее статическое связывание же, насколько я знаю. Оно превращается в имя дочернего класса

2018-11-18 20:20 UTC, ilyatos commented on monitor-api/components/models/BaseModel.php
> +            $object = new static();
кстати, придумал, как улучшить

2018-11-18 20:22 UTC, ilyatos commented on monitor-api/components/base/Error.php
> +
разве нужно в каждом файле? я думал это работает, как один раз подключил в index, так всё

2018-11-19 13:47 UTC, neSpecc requested changes

2018-11-19 13:47 UTC, neSpecc commented on monitor-api/components/models/BaseModel.php
> +     * Base sync for child
не понятное описание метода. Нужно написать, зачем он нужен и как работает

2018-11-19 20:02 UTC, neSpecc approved these changes

2018-11-19 20:05 UTC, talyguryn approved these changes

2018-11-19 20:25 UTC, merged