Add README
codex-team/uptime-monitor.server pull request #4
Opened 2018-11-22 21:21 UTC by ilyatos

2018-11-25 22:53 UTC, khaydarov requested changes

2018-11-25 22:53 UTC, khaydarov commented on README.md
> +1. Everything about PHP
чет вообще не понятно

2018-11-25 22:53 UTC, khaydarov commented on README.md
> +1. Everything about PHP
ты рассказываешь как php установить на локальной машине или в докер окружении?

2018-11-28 16:20 UTC, khaydarov approved these changes

2018-11-29 15:52 UTC, neSpecc approved these changes

2018-11-29 15:59 UTC, n0str approved these changes

2018-11-29 16:05 UTC, talyguryn approved these changes

2018-11-29 17:02 UTC, merged