Hawk base models
codex-team/uptime-monitor.server pull request #8
Opened 2018-12-23 16:33 UTC by ilyatos

Базовая реализация моделей без добавления в Query/Mutation (будет следующим реквестом).

2019-01-18 20:54 UTC, n0str approved these changes

2019-01-18 20:59 UTC, khaydarov requested changes

2019-01-18 20:59 UTC, khaydarov commented on hawk-api/components/models/Archive.php
>       * @throws \Exception
Именно эта функция не выплевывает эксепшн. Да и любая ошибка наследует класс exception, писать нет смысла, это ничего не даст. А вот если бы это была ошибка \Custom_Exception, то лучше указывать, чтобы в iDE видеть какой именно эксепшн и его обрабатывать либо падать

2019-01-18 20:59 UTC, khaydarov commented on hawk-api/components/models/BaseModel.php
> +     * @throws \Exception
лишняя строчка

2019-01-18 20:59 UTC, khaydarov commented on hawk-api/components/models/BaseModel.php
> +     * @return array|null|object
а нельзя ли работать с каким-то одним типом? просто если ты добавишь в ретурн string и int, то получается, что функция может вернуть все что угодно и с каким угодно типом. Лучше хотя бы знать array|null, int|null, string|null и тд. array|object|null - перебор. Если бы мы писали на статически типизированных языках, то в данном случае ты бы не смог написать функцию, которая принимала бы и массив и нул и объект. Да и в php не напишешь.
Ты же не сможешь сделать
```php
function (array|object $arg) { 
  ... работать с arg
}
```
поэтому значение, которое вернет эта функция никто нормально не обработает, даже если и сделает, то будет никому не очевидно.

2019-01-18 21:05 UTC, ilyatos commented on hawk-api/components/models/BaseModel.php
> +     * @return array|null|object
Да, понимаю проблему. Сам смотрю и в недоумении как так вышло, всегда возвращается только array, никакого object.

2019-01-18 21:06 UTC, ilyatos commented on hawk-api/components/models/Archive.php
>       * @throws \Exception
Вопрос, почему IDE ругается тогда, если нижевызываемая функция кидает исключение, то  требуется указать его выброс и в вышевызываемой. Как тут, например. и в BaseModel

2019-01-18 21:07 UTC, ilyatos commented on hawk-api/components/models/Archive.php
>       * @throws \Exception
И в каком месте его лучше обрабатывать? по сути, если человек пытается обновить несуществующую запись, то это определенно исключение, но вот выброшу я его, а что делать дальше?

2019-01-19 12:02 UTC, neSpecc requested changes

2019-01-19 12:02 UTC, neSpecc commented on hawk-api/components/models/BaseModel.php
> +    abstract public function collectionName(): string;
надо бы описать методы

2019-01-19 12:02 UTC, neSpecc commented on hawk-api/components/models/BaseModel.php
> +     * @param array $args
не описан параметр

2019-01-19 12:02 UTC, neSpecc commented on hawk-api/components/models/BaseModel.php
> +    public function all(array $conditions = []): array
не описан параметр

2019-01-19 12:02 UTC, neSpecc commented on hawk-api/components/models/Membership.php
> +    public $tgHook;
где-то андерскор, где-то camelCase. Надо определиться с именованием (обсуждаемо), обозначить его в конфиге php_cs_fixer и использовать везде в одном стиле

2019-01-19 12:02 UTC, neSpecc commented on hawk-api/components/models/Project.php
> +     * URO
```suggestion
     * Project's website
```

2019-01-19 12:02 UTC, neSpecc commented on hawk-api/components/models/Project.php
> +    public $id_added;
может лучше uid_added? или creator

2019-01-19 12:58 UTC, khaydarov commented on hawk-api/components/models/Archive.php
>       * @throws \Exception
ты написал throws exception там, где он не выбрасывается. Просто строчка лишняя. 

В каких случаях используется exception:
```
function divide($a, $b) {
    return $a / $b;
}
```

Если $b будет 0, то функция вернет ошибку (exception), потому что делить на 0 нельзя. 
Что ответит сервер?
сервер вернет http с 500 кодом и с текстом ошибки. Пользователь увидит много лишнего, например, текст ошибки, backtrace, кусочки твоего кода, путь к файлу и тд. 

А если сделаем так:
``` 
/**
 * ...
 * @throws My_Custom_Exception
 */
function divide($a, $b) {
    if ($b === 0) {
        throw new My_Custom_Exception('You are trying to divide by 0');
    }
    return $a/$b;
}
```

а функция, которая вызывает эту функцию (выше уровнем)
```
function calculateMe() {
   $a = 3;
   $b = 0;
   try {
     $this->divide(3, 0);
   } catch (My_Custom_Exception $e) {
        // do something..
        // например, ты можешь вернуть 0 в таких случаях, если это не критично (например, в вышней математике можно сказать что это бесконечность и так и вернуть в ответ клиенту)
     // можно перевести текст ошибки на русский, читаемый...
   }
   
   return ....
}

2019-01-19 13:03 UTC, khaydarov commented on hawk-api/components/models/Archive.php
>       * @throws \Exception
Я просто контекста не знаю в твоем случае. Если человек пытается что-то сделать с несуществующей моделью, то ты в модели выбрасываешь exception, а в контроллере отлавливаешь и отвечаешь нормально. Можешь статус код поменять, можешь перевести или что-то еще

2019-01-19 14:15 UTC, ilyatos commented on hawk-api/components/models/Archive.php
>       * @throws \Exception
Понял, спасибо

2019-01-19 14:23 UTC, ilyatos commented on hawk-api/components/models/Membership.php
> +    public $tgHook;
@neSpecc Проще использовать подчёркивания именно для полей, так как будет однозначное соответствие между полями в монге и свойствами модели. А свойства для нужд самой модели именовать уже в camelCase. Вот такое предложение

2019-01-19 23:29 UTC, talyguryn requested changes

2019-01-19 23:29 UTC, talyguryn commented on hawk-api/components/models/Membership.php
> +    // TODO: разобраться с "collection:<user._id>"
что этот туду значит?

2019-01-19 23:29 UTC, talyguryn commented on hawk-api/components/models/Membership.php
> +    public function collectionName(): string
это нельзя вынести в абстрактную функцию и не прописывать в моделях, если не нужно как-то изменять ответ?

2019-01-19 23:29 UTC, talyguryn commented on hawk-api/components/models/Team.php
> +        return self::COLLECTION_NAME;
с айдишником же надо вернуть или я чего-то не понимаю? в других подобных моделях то же самое

2019-01-19 23:29 UTC, talyguryn commented on hawk-api/schema/Types/Project.php
> +                    'id_added' => [
id_added? такое себе

2019-01-19 23:29 UTC, talyguryn commented on hawk-api/schema/Types/Team.php
> +                    'user_id' => [
если это id одного какого-то юзера, то я не понимаю структуры бд

2019-01-20 08:35 UTC, ilyatos commented on hawk-api/components/models/Team.php
> +        return self::COLLECTION_NAME;
где-то требуется с айдишником, а где-то без. Например "users" нет айдишника. Это как раз та проблема, над которой я думаю и это относится к TODO, который в классах, где нужен айдишник

2019-01-20 08:37 UTC, ilyatos commented on hawk-api/components/models/Membership.php
> +    public function collectionName(): string
Немного не понял. Эта функция и так абстрактная в базовой модели. Её нельзя не переопределять, потому что у всех моделей разные коллекции.

2019-01-20 08:41 UTC, ilyatos commented on hawk-api/schema/Types/Team.php
> +                    'user_id' => [
<img width="284" alt="2019-01-20 11 40 15" src="https://user-images.githubusercontent.com/25087524/51436990-345b6880-1ca8-11e9-8923-f180dac8d053.png">
Да, одного юзера. Ты мне сам это и рассказывал, когда объяснял структуру бд

2019-01-20 15:13 UTC, ilyatos commented on hawk-api/components/models/Membership.php
> +    // TODO: разобраться с "collection:<user._id>"
Я пока не знаю как реализовать динамическое название коллекции. есть одна идея, но такое себе.

2019-01-21 21:42 UTC, neSpecc commented on hawk-api/components/models/BaseModel.php
> +    protected function findOneWrapper(array $filter = []): array
ты имел ввиду private?

2019-01-21 21:42 UTC, neSpecc commented on hawk-api/components/models/BaseModel.php
> +    public function assocCollection(): Collection
этот метод точно надо делать публичным?

2019-01-21 21:42 UTC, neSpecc commented on hawk-api/components/models/Membership.php
> +    public function collectionName(): string
а это не приватная функция должна быть? она будет снаружи этой модели использоваться?

2019-01-21 21:42 UTC, neSpecc commented on hawk-api/components/models/Membership.php
> +    protected const COLLECTION_NAME = 'membership:';
может private COLLECTION_NAME_PREFIX?

2019-01-22 16:24 UTC, ilyatos commented on hawk-api/components/models/BaseModel.php
> +    public function assocCollection(): Collection
не точно, сделал protected, чтобы можно было в наследниках юзать (это будет надо)

2019-01-22 16:24 UTC, ilyatos commented on hawk-api/components/models/Membership.php
> +    public function collectionName(): string
будет приватная, поправил

2019-01-22 16:54 UTC, khaydarov requested changes

2019-01-22 16:54 UTC, khaydarov commented on hawk-api/components/models/Archive.php
> +    private const COLLECTION_NAME = 'archive';
предлагаю сделать лучше и сократить код.

1) В BaseModel делаем свойство protected $collectionName = '';
2) Функцию называем getCollectionName в BaseModel и напишем return $this->collection_name;
Таким образом ты можешь выпилить в большинстве моделей эту функцию. 

Protected мы делаем для того, чтобы можно было наследовать. У тебя в membership коллекции получаются динамически, можешь и в этом классе реализовать.

А еще в функции 
```php
getCollectionName() {
    if (empty($this->collection_name)) {
          throw new BaseModelException('Collection name is not defined');
          // так ты сразу поймешь, что в модели свойство не перекрыто
    }
    return $this->collection_name;
}
```

2019-01-22 19:59 UTC, ilyatos commented on hawk-api/components/models/Archive.php
> +    private const COLLECTION_NAME = 'archive';
Понял логику, хорошее решение. Только получается, что для моделей с динамическим названием коллекции нужно будет переопределять этот метод, верно? Для них практически ничего не изменится

2019-01-22 20:45 UTC, neSpecc approved these changes

2019-01-22 21:01 UTC, khaydarov requested changes

2019-01-22 21:01 UTC, khaydarov commented on hawk-api/components/models/BaseModel.php
> +            throw new RecordNotFoundException($this->collectionName());
Когда PHP выплюнет эту ошибку, ты никогда не поймешь в чем именно проблема если не будешь знать стека. Особенно когда кода много. 

Раз делаешь кастомный эксепшн, то передай хоть какой-то нибудь текст, по которому и ты и пользователь поймете, что что-то то не так. А то тут может быть:
'', 'collectionName', '323123' ...

```php
throw new RecordNotFoundException(sprintf("No records found in collection `%s`", $this->collectionName()));
```

2019-01-22 21:01 UTC, khaydarov commented on hawk-api/components/models/BaseModel.php
> +            throw new RecordNotFoundException($this->collectionName());
И тут добавить бы текст ошибки. Можно сделать лучше: написать что-то не найдена запись при обновлении в функции update, а тут при поиске

2019-01-22 21:45 UTC, khaydarov approved these changes

2019-01-22 21:53 UTC, talyguryn approved these changes

2019-01-22 21:54 UTC, merged